# Acknowledgments
This thesis would not have been possible without the support and assistance of many individuals. I would like to express my sincere gratitude to everyone who helped me in the process of writing this thesis. To my loved ones, thank you for your patience, support, and the time you have sacrificed during this project. I want to thank Antoinette Kroes for her valuable assistance on appropriately calculating effect sizes for ANOVA models that include within-subject factors. Furthermore, I want to express my gratitude for my mentor, Tom Wilderjans, for his support and guidance throughout challenging phases. I also would like to thank Wouter Weeda for serving as the second reader of my thesis and for supervising me during my internship at the credit management company from which this thesis originated. Finally, I would like to express my gratitude to my supervisor, Mark de Rooij. Thank you for your patience, guidance, support, and the time you have dedicated to this project. I especially appreciate the cheerful and positive attitude with which you have approached our collaboration throughout this process.

\newpage