# Abstract 
Class imbalance is common in real-world data and creates challenges at every stage of the classification process. Crucial is the selection of adequate evaluation metrics, but generally accepted solutions for multiclass imbalanced scenarios are lacking. This thesis proposes a class-balanced version of Matthews correlation coefficient (MCC~cb~) and investigates whether this metric is an adequate solution to address the limitations found in commonly used metrics (Accuracy, F1~m~, and MCC) in imbalanced learning. Four simulation studies were conducted to enable a multifaceted approach for examining the behavior of metrics extensively in various scenarios, including previously understudied conditions. The appropriateness of metric behavior was assessed based on a credit management case study wherein the objective was to find a metric that prioritizes the representation of the performance of underrepresented class(es) without compromising that of overrepresented class(es). The impact of class imbalance, class compositions (multi-minority, multi-majority, and mixed), and misclassification patterns on metric behavior was analyzed, using mixed-model ANOVAs for a systematic statistical comparison while accounting for the non-independence of errors in each study. The results demonstrated that MCC~cb~ is an adequate metric in multiclass (im)balanced scenarios. Despite the critiques in previous research, F1~m~ was not found to be misleading considering the objective. Hence, both F1~m~ and MCC~cb~ could be considered as suitable metrics, depending on which best accommodates the user's needs and preferences. For the case study, MCC~cb~ is most in line with their preferences, thus MCC~cb~ would be the most appropriate metric. This thesis contributes to the domain of imbalanced classification by introducing MCC~cb~, as a familiar yet more appropriate evaluation metric than MCC in multiclass imbalanced scenarios, and by expanding the knowledge on metric behavior of existing metrics in various scenarios to aid in metric selection.

*Keywords:* evaluation metrics, multiclass imbalance, imbalanced classification, class-balanced Matthews correlation coefficient

\newpage